### ISSUE TITLE
QR camera view on iOS is not full screen.

### ISSUE THREAD

**Issue by jonentropy** [villela/flutter_qrcode_reader#8]
Device was iPhone 5S.
The scanning barcode view was not full screen, as it is on Android.
Instead it displayed inside a smaller view.

**Comment by villela** [comment]
please send a pull request with the fix

**Comment by johanhenselmans** [comment]
The reason it is not full-screen was because I wanted to have a back button. If you make it full screen you have to implement a back-button yourself.
